<Project>
  <Import Project="../Directory.Build.props" />
  <PropertyGroup><EnableDynamicLoading>true</EnableDynamicLoading></PropertyGroup>
  <ItemGroup><ProjectReference Include="../../src/Golemancer.Contracts/Golemancer.Contracts.csproj"><Private>false</Private><ExcludeAssets>runtime</ExcludeAssets></ProjectReference></ItemGroup>
  <Target Name="StageObjectPack" AfterTargets="Build">
    <MakeDir Directories="$(MSBuildProjectDirectory)/../../Content/Packs/$(PackDirectory)/Bin/$(TargetFramework)" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(MSBuildProjectDirectory)/../../Content/Packs/$(PackDirectory)/Bin/$(TargetFramework)" />
    <Copy Condition="Exists('$(TargetDir)$(AssemblyName).deps.json')" SourceFiles="$(TargetDir)$(AssemblyName).deps.json" DestinationFolder="$(MSBuildProjectDirectory)/../../Content/Packs/$(PackDirectory)/Bin/$(TargetFramework)" />
  </Target>
</Project>
