using System.Text.Json;
using PackEngine.Workspace;

// Invoked only against the temporary copy made by verify-resident.py.
var session = new EditorSession(args[0], args[1]);
using var runner = new ProjectRunner(session, args[2]);
const string file = "Content/Packs/02.Controls/ui.xml", key = "widget:golemancer.costButton";
int checks = 0;
void Check(bool condition, string message) { if (!condition) throw new Exception(message); Console.WriteLine("PASS: " + message); checks++; }
async Task Reject(Func<Task> action, string message)
{ try { await action(); } catch (Exception e) when (e is InvalidOperationException or IOException or InvalidDataException or ArgumentException) { Check(true, message); return; } throw new Exception(message); }
Task<string> Tool(AgentWorkspace host, string name, object arguments, CancellationToken token = default) => host.CallAsync(name, JsonSerializer.SerializeToElement(arguments), token);

var open = session.Open(file); string original = open.Text;
const string portablePack = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
session.SetPointingMode("single"); session.Point(key); session.Point("view:golemancer.purchase", "tree", true);
Check(session.Pointing.Targets.Count == 2, "Exactly Yogi additive pointing preserves both explicitly chosen objects");
var sharedState = session.CaptureSharedContext(portablePack, "State");
Check(sharedState.Documents.Count == 1 && sharedState.Context.Count == 0 && sharedState.Targets.Count == 0 && sharedState.Packs.Count > 0, "shared editor state contains open versions and pack IDs without inheriting pointing or file bodies");
var sharedExact = session.CaptureSharedContext(portablePack, "ExactlyYogi");
Check(sharedExact.Targets.Count == 2 && sharedExact.Context.Count == 2 && sharedExact.Context[0].Content.Contains("fontSize"), "Exactly Yogi shares actual bounded definitions from the explicitly pointed objects");
sharedExact.Documents.Add(new() { Path = "unselected-open-document.xml" }); sharedExact.Packs.Add("unselected-pack");
var yogiFile = YogiAttachment.Create(sharedExact); string yogiText = System.Text.Encoding.UTF8.GetString(yogiFile.Bytes);
Check(yogiFile.Name.EndsWith(".txt") && yogiText.Contains("fontSize") && yogiText.Contains(sharedExact.Context[0].DocumentHash) && !yogiText.Contains("unselected-open-document") && !yogiText.Contains("unselected-pack"),
    "chat attachment contains selected definitions and observed versions, without unrelated open documents or pack inventory");
await Reject(() => Task.FromResult(YogiAttachment.Create(sharedState)), "ordinary state and navigation cannot become an implicit chat attachment");
var unsafeYogi = SharedEditorProtocol.Freeze(sharedExact); unsafeYogi.Id = "../outside";
await Reject(() => Task.FromResult(YogiAttachment.Create(unsafeYogi)), "attachment names cannot escape their local staging directory");
byte[] capturedPng = [137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 0];
var lookSnapshot = new SharedEditorSnapshot { Kind = "LookAtYogi", Image = new() { Data = Convert.ToBase64String(capturedPng), Sha256 = WorkspaceProject.Hash(capturedPng) } };
var lookFile = YogiAttachment.Create(lookSnapshot);
Check(lookFile.Name.EndsWith(".png") && lookFile.MediaType == "image/png" && lookFile.Bytes.SequenceEqual(capturedPng), "Look At Yogi stages the exact captured PNG bytes");
lookSnapshot.Image.Sha256 = "changed";
await Reject(() => Task.FromResult(YogiAttachment.Create(lookSnapshot)), "changed capture bytes cannot be silently attached under an earlier snapshot");
var remoteOrdinary = session.PrepareSharedTask("web task", "preserve the existing price label", null);
Check(remoteOrdinary.Context.Count == 0 && remoteOrdinary.Input.Targets.Count == 0 && session.Pointing.Targets.Count == 2 && remoteOrdinary.Prompt.Contains("preserve the existing price label"), "web work receives caller-provided conversation context without consuming the user's pending pointing");
var remoteExact = session.PrepareSharedTask("inspect this", "", sharedExact);
Check(remoteExact.Input.Targets.Count == 2 && remoteExact.Context[0].DocumentHash == sharedExact.Context[0].DocumentHash, "web tasks import immutable observed context without a conversation URL");
sharedExact.Context[0].Content = "modified after send";
Check(System.Text.Encoding.UTF8.GetString(yogiFile.Bytes) == yogiText && !yogiText.Contains("modified after send"), "later selection changes do not mutate an attachment already staged for the composer");
Check(remoteExact.Context[0].Content.Contains("fontSize"), "later changes to a shared object cannot mutate the imported request");
var sharedDocument = session.CaptureSharedContext(portablePack, "Document", file);
Check(sharedDocument.Context.Count == 1 && sharedDocument.Targets.Count == 0 && sharedDocument.Context[0].Content == original.Substring(0, Math.Min(12000, original.Length)), "document sharing includes only the explicitly chosen open document and its character limit");
int beforeStale = session.State.Requests.Count; open.Text += "\n";
await Reject(() => Task.FromResult(session.PrepareSharedTask("stale work", "", sharedDocument)), "web work rejects a document changed since its shared snapshot");
Check(session.State.Requests.Count == beforeStale, "rejected stale web work does not leave a prepared phantom request");
open.Text = original;
var journal = new SharedEditorTaskJournal { TaskId = Guid.NewGuid().ToString(), SessionId = Guid.NewGuid().ToString(), ClaimId = Guid.NewGuid().ToString(), State = "started", RequestId = remoteExact.Id };
session.SaveSharedTask(journal); var restoredJournal = session.LoadSharedTask(journal.TaskId)!;
Check(restoredJournal.State == "started" && restoredJournal.ClaimId == journal.ClaimId && restoredJournal.RequestId == remoteExact.Id, "durable local claims distinguish interrupted execution from an unstarted task");
await Reject(() => Task.FromResult(session.SharedTaskPath("../outside")), "web task journals cannot address paths outside the local state folder");
Check(SharedEditorProtocol.IsPage(SharedEditorProtocol.Page) && !SharedEditorProtocol.IsPage(SharedEditorProtocol.Page.Replace(".site", ".site.evil.test")) && !SharedEditorProtocol.IsPage(SharedEditorProtocol.Page + "/other") && !SharedEditorProtocol.IsPage("http://packengine-links.jorodane.chatgpt.site/editor-bridge"), "editor sharing accepts messages only from its exact authenticated HTTPS page");
File.WriteAllText(Path.Combine(args[1], "shared-contract.json"), SharedEditorProtocol.Serialize(sharedDocument));
session.SetPointingMode("none");
session.Select(key); session.Point(key);
var ordinary = session.PrepareContext("ordinary chat");
Check(ordinary.Context.Count == 0 && ordinary.Input.Targets.Count == 0 && ordinary.Documents.Count == 1, "navigation and open tabs do not attach content to ordinary chat");
session.SetPointingMode("single"); session.Point(key, "tree");
var snapshot = session.PrepareContext("change this definition");
snapshot.WritablePacks.Add("golemancer.controls"); snapshot.Target = "linux";
Check(snapshot.Context.Count == 1 && snapshot.Context[0].Content.Contains("fontSize") && !snapshot.Context[0].Content.Contains("<View"), "single pointing captures just the definition with its document version");
session.SetPointingMode("range"); session.Point("view:golemancer.purchase", "graph"); session.Point("widget:golemancer.button", "graph");
Check(snapshot.Input.Targets.Single().Key == key && snapshot.Input.Mode == "single", "later pointing and mode changes cannot alter an already captured request");
var multiple = session.PrepareContext("these two");
Check(multiple.Input.Targets.Count == 2 && multiple.Context.Count == 2, "range pointing captures the explicit set of object identities");
session.PointRange(file, 1, 2); var range = session.PrepareContext("these lines");
Check(range.Input.Targets.Single().StartLine == 1 && range.Input.Targets.Single().EndLine == 2 && range.Context.Single().Content.Split('\n').Length == 2, "text range captures line bounds and selected text without screen pixels");
open.Text += "\n";
await Reject(() => Task.FromResult(session.PrepareContext("stale range")), "editing a pointed text range requires selecting it again");
open.Text = original; session.SetPointingMode("none");
using var readonlyHost = new AgentWorkspace(session, ordinary, runner, action => action());
await Reject(() => Tool(readonlyHost, "packengine_build", new { pack = "golemancer.controls" }), "a read-only request cannot build a pack");
await Reject(() => Tool(readonlyHost, "packengine_project", new { operation = "verify" }), "a request without command scope cannot run project verification");
using var host = new AgentWorkspace(session, snapshot, runner, action => action());
await Reject(() => Tool(host, "packengine_read", new { path = "../outside" }), "tool reads reject paths outside the project");
await Reject(() => Tool(host, "packengine_read", new { path = "README.md" }), "tool reads reject undeclared files within the project");
var read = JsonDocument.Parse(await Tool(host, "packengine_read", new { path = file, startLine = 1, lineCount = 2 })).RootElement;
string hash = read.GetProperty("DocumentHash").GetString()!;
Check(read.GetProperty("Partial").GetBoolean() && read.GetProperty("Content").GetString()!.Split('\n').Length == 2, "demand reads are bounded slices with a full document hash");
object Patch(string expected) => new { path = file, expectedHash = expected, oldText = "property=\"fontSize\" value=\"13\"", newText = "property=\"fontSize\" value=\"15\"", intent = "verification only" };
await Reject(() => Tool(host, "packengine_patch", Patch("stale")), "patch rejects a document version the model did not observe");
open.Text += "\n";
await Reject(() => Tool(host, "packengine_patch", Patch(hash)), "patch cannot overwrite an unsaved user buffer");
open.Text = original;
string disk = session.Project.Resolve(file); byte[] bytes = File.ReadAllBytes(disk);
File.AppendAllText(disk, "\n");
await Reject(() => Tool(host, "packengine_patch", Patch(hash)), "patch detects disk changes even when the open buffer still matches");
File.WriteAllBytes(disk, bytes);
await Reject(() => Tool(host, "packengine_patch", new { path = "Content/Packs/40.Commerce/actions.xml", expectedHash = hash, oldText = "x", newText = "y", intent = "outside scope" }), "the agent cannot edit a different pack");
var preview = JsonDocument.Parse(await Tool(host, "packengine_patch", Patch(hash))).RootElement;
string change = preview.GetProperty("ChangeId").GetString()!;
Check(File.ReadAllBytes(disk).SequenceEqual(bytes), "agent preview produces a reviewable diff without applying it");
await Reject(() => Tool(readonlyHost, "packengine_apply", new { changeId = change }), "a different turn cannot apply another request's preview");
await Tool(host, "packengine_apply", new { changeId = change });
Check(File.ReadAllText(disk).Contains("property=\"fontSize\" value=\"15\""), "authorized apply changes the real project XML");
await Tool(host, "packengine_build", new { pack = "golemancer.controls" });
session.Apply(change, true);
Check(File.ReadAllBytes(disk).SequenceEqual(bytes), "agent changes retain exact-byte undo");
Check(session.State.Operations.Any(o => o.Status == "failed") && session.State.Operations.Any(o => o.Tool == "packengine_apply" && o.Status == "completed") && session.State.Reads.Count > 0,
    "read receipts and failed/completed actions remain separately inspectable");
var settings = new AssistantSettings(); var projectAccess = settings.Register(session.Project);
Check(settings.ShouldConnect(projectAccess), "a user-opened project defaults to automatic connection without an inference request");
projectAccess.Enabled = false;
Check(!settings.ShouldConnect(projectAccess) && !settings.Connection(projectAccess, "codex", session.StateDirectory).AccessEnabled, "project access gates both automatic startup and provider connection");
projectAccess.Enabled = true; settings.ConnectionEnabled = false;
Check(!settings.ShouldConnect(projectAccess), "global connection denial overrides project access");
settings.ConnectionEnabled = true; settings.AutoConnect = false;
Check(!settings.ShouldConnect(projectAccess) && settings.Connection(projectAccess, "codex", session.StateDirectory).AccessEnabled, "manual connection remains possible when only auto-connect is disabled");
projectAccess.HistoryEnabled = false; projectAccess.BlockedThreads.Add("denied");
var options = settings.Connection(projectAccess, "codex", session.StateDirectory); projectAccess.BlockedThreads.Clear();
Check(!options.HistoryEnabled && options.BlockedThreads.Single() == "denied", "connection permission snapshots do not follow later UI mutations");
var shared = new SharedChatReference { Title = "Web design notes", Url = "https://chatgpt.com/c/user-selected", Content = "first\nsecond\nthird", Shared = true };
projectAccess.WebChats.Add(shared); projectAccess.WebChats.Add(new() { Title = "Private", Url = "https://chatgpt.com/c/private", Content = "secret" });
var contextRequest = session.PrepareContext("use the selected web context"); contextRequest.SharedChats = projectAccess.CaptureSharedChats();
Check(contextRequest.SharedChats.Count == 1 && contextRequest.Context.Count == 0, "web context capture includes only explicitly shared entries and no automatic file context");
using var sharedHost = new AgentWorkspace(session, contextRequest, runner, action => action());
shared.Content = "changed later"; shared.Shared = false; contextRequest.SharedChats[0].Content = "also changed later";
var sharedRead = JsonDocument.Parse(await Tool(sharedHost, "packengine_read", new { path = shared.Path, startLine = 2, lineCount = 1 })).RootElement;
Check(sharedRead.GetProperty("Content").GetString() == "second" && sharedRead.GetProperty("Partial").GetBoolean(), "shared chat reads are bounded and frozen at send time");
Check(session.State.Reads.Any(r => r.Request == contextRequest.Id && r.Path == shared.Path), "demand reads of shared context have separate read receipts");
await Reject(() => Tool(sharedHost, "packengine_read", new { path = projectAccess.WebChats[1].Path }), "unshared chat context is inaccessible to tools");
await Reject(() => Tool(sharedHost, "packengine_patch", new { path = shared.Path, expectedHash = "x", oldText = "first", newText = "edit", intent = "invalid" }), "shared web context never becomes a writable project document");
await Reject(() => Task.FromResult(SharedChatReference.ValidateUrl("https://chatgpt.com.evil.invalid/c/123")), "web links reject lookalike domains");
await Reject(() => Task.FromResult(SharedChatReference.ValidateUrl("file:///tmp/private")), "web links reject local-file protocols");
var settingsPath = Path.Combine(session.StateDirectory, "preferences", "assistant-settings.json"); settings.Save(settingsPath);
var restored = AssistantSettings.Load(settingsPath);
Check(!restored.AutoConnect && !restored.Projects.Single().HistoryEnabled && restored.Projects.Single().WebChats.Count == 2, "connection, project, history and shared-context preferences survive restart");
await SharedTaskVerification.Run(session, runner, Check);
await ReviewVerification.Run(session, runner, Check);
await ReviewRetryVerification.Run(session, runner, Check);
await CollaborationVerification.Run(session, runner, Check);
Console.WriteLine("RESIDENT_WORKSPACE_PASS " + checks);
