using Confectory.Editor.Contracts;

namespace Confectory.EditorPacks;

// Available through confectory_editor(api), even when host sources are outside the project.
public static class EditorProjectDataApi
{
    public static object Describe() => new
    {
        Assembly = "Confectory.Editor.Contracts.dll", Contract = "editor-1", Api = "project-data-1",
        Command = typeof(EditorProjectCommand).FullName,
        Service = typeof(IEditorProjectData).FullName,
        Methods = new[] { "IReadOnlyList<EditorProjectDocumentInfo> ListDocuments(string pack = \"\")", "EditorProjectDocument ReadDocument(string path, int maximumCharacters = 200000)" },
        CatalogApi = "project-catalog-1; optional IEditorProjectCatalog on the same project service",
        CatalogMethods = new[] { "IReadOnlyList<EditorProjectObject> ListObjects(string kind = \"\", string pack = \"\", string query = \"\")", "IReadOnlyList<EditorProjectAsset> ListAssets(string pack = \"\")", "EditorProjectAssetData ReadAsset(string path)" },
        Object = new[] { "Key", "Id", "Kind", "Title", "Pack", "Path", "Status", "Category", "Icon", "Browsable" },
        ConceptWorkspace = new
        {
            Api = "concept-space-1", Documentation = "docs/PROJECT_SPACE.md",
            Registration = "EngineProject/ConceptSpace mainPack=PackId contains Pack id/schema/objects/views. Each registered document is a pack-owned Data file. New projects have empty documents in Main Pack immediately; edit the appropriate observed document through normal reviewed project proposals.",
            Schema = "ConceptSchema version=1: Category(id,name,symbol,parent category ID), Concept(id,name,symbol,category category ID,extends concept ID), nested Field(id,name,type,kind,multiple). type is text/number/boolean or a stable Concept ID; kind is normal/composite/function; function type is its return type and also allows void. Field children are composite members or function parameters. Categories classify; concepts are leaves; extends enters a Variation layer. Omitted fields inherit; additions preserve existing contracts and stable member IDs.",
            Data = "ConceptObjects version=1: Object(id,name,concept,icon) with Value(field,text), nested Value members and repeated Item values. Typed references store stable object IDs. Source Pack is determined by its owning document, not a Field or Value. Implementation(id,name,symbol,handler,returns,source) has input Field definitions; function Values hold the matching Implementation ID. Matching is a static name/parameter/cardinality/return contract check; it does not prove runtime execution.",
            Views = "ConceptViews version=1: View(id,name,symbol,concept,layout=table|cards|slots|pack,editor optional ObjectEditor ID,sourcePack=true optional). Field(path,label,side=input|output optional,icon optional member ID,quantity optional member ID). Slash-separated paths use Field IDs, including composite and repeated members. Columns may select a subset of schema fields for balancing. Several Views may bind the same data. Change only this document to change presentation; preserve Schema and Object documents.",
            CustomEditors = "Built-in Views offer table, cards and editable input/output icon slots. For arbitrary behavior, create a reviewed editor-1 pack, register an ObjectEditor kind=concept.<ConceptId>, and bind a pack-layout View to its ID. Catalog object Key=concept-object:<ObjectId>; project service and editor.object.pack expose the actual Source Pack. Return DocumentChanges to edit the same data after observed-version checks. No dedicated View is required: the schema table always remains available.",
            Ownership = "All elements have stable IDs independent of Pack and Namespace. References use those IDs. The owning pack's namespace plus symbol forms the logical address independently of source paths. Pack migration moves the declarations between owner documents, keeps IDs/references, updates inferred dependencies and links function source without relocating its physical file. FunctionAssembly declares a built function library separately from engine module Assembly entries."
        },
        ElementsApi = "project-elements-1; optional IEditorProjectElements on the same command-scoped service",
        ElementMethods = new[] { "ListElementTypes()", "ListElementPacks()", "ReadElement(key)", "GetObservedValues(pack, kind, element, field) [optional IEditorProjectObservedValues]", "ProposeElement(EditorElementEdit)", "ProposeNewElement(EditorElementCreate)" },
        ElementModel = "ReadElement returns Object, DocumentHash, Editable/Draft/DiskChanged, relative node Paths, fields (Value/Present/Type/Required/ReadOnly/ReferenceKind/Options), children and creation templates. Existing strings are suggestions, enums are declared constraints and references remain static metadata. IndexRules Symbol declares category/categoryAttribute/icon/iconAttribute; Authoring declares collection/template/Field/Child. Symbols also classify UI XML. Browsable=false hides native aliases while retaining their reference identities.",
        ElementProposals = "ProposeElement uses Key + the displayed ExpectedHash and 1..200 mutations: attribute/name/value, leaf text/value, child/name/value/optional append Index. Paths are . or ./*[n] chains inside that element. Root identity cannot change; declared field/child rules, editability, clean source and observed versions are checked. ProposeNewElement chooses Kind/Pack/Name and optional Id, resolves one existing declared collection, uses its project template/defaults, and creates no arbitrary file. Return the resulting EditorDocumentChange in DocumentChanges; saving always follows the host's review.",
        Asset = "Path/Pack/MediaType/Readable; ReadAsset adds Hash and DataUrl. Only pack.xml <Asset path=...> or project IndexRules <Asset select=XPath attribute=...> resources can be read; 2 MB bitmap limit. SVG paths are metadata only. Object kinds and icon semantics belong to the consumer's index rules and DLL, not the engine.",
        ExtensionRegistration = "pack.xml: editor-1, Ui path, Data path, Assembly Bin/{framework}/...dll, Source csproj. editor.xml: EditorExtensions version=1; Panel(slot,view,title), Window(id,view,title,autoOpen), Command(id,handler,payload plus Argument name/value). Panel/window lifecycle is independent of DLL loading. read returns declared XML and implementation sources; inspect returns saved/proposed definitions separately from live inherited views.",
        Widgets = "editor.stack/text/button/input/wrap/slot on Windows and Android. wrap provides native flow layout; slot has image=data URL, glyph<=32 chars, count=nonnegative integer, value=selection key, tint=#RRGGBB, tooltip. Slot activate has Text payload equal to value. A trailing plus slot uses glyph=+ and count=0. No game item type is embedded in these widgets.",
        Navigation = "EditorExtensions Navigation(id,extends,title,surface=menu|hotbar|navigation,group,order plus exactly one command/window/category; optional Text payload). All registered windows are also available in the host's default window menu. Same-surface derived entries replace their ancestor; different surfaces retain both. Opening a project does not execute newly discovered project DLLs.",
        ObjectEditor = "ObjectEditor(id,extends,kind=*|project kind,category optional subtree,title,window,command optional Text initializer,priority). Highest priority then exact kind and category specificity chooses the editor; kind-specific children retain a generic ancestor fallback. EditorCommandResult.OpenObject { Key, EditorId optional, ChooseEditor } binds the object and opens/focuses its window; initialization receives its Key. OpenXml=Key explicitly opens the source. Context freezes project/projectId, windowId/nodeId, editorPack and bound objectKey/objectKind/objectTitle/objectPack/objectEditor; UI bindings expose editor.object.key/kind/title/pack. Continue { Command, Payload } requests a fresh same-pack Text invocation after review/output processing; cancelled review does not continue.",
        TransientView = "EditorCommandResult.View = new EditorViewUpdate { WindowId, Xml }. Exactly one owned <pack>.dynamic.* Ui/View, no Widget or Contribution declarations. Target must be an owned registered window/panel. Windows and Android preflight the full definition, retain the window and reuse controls by (Node ID, widget, renderer), updating only changed properties/layout and child positions. Matching roots stay attached; no close/open or full content clear occurs. Closing/reopening or module reload restores declared XML. Runtime views do not write source files.",
        TransientInput = "Use deterministic IDs from object Key + subpath + property, never row numbers, current values or GetHashCode. Keep each object's container identity stable. Unchanged text declarations preserve local input; equal text echoes do not assign native text or reset caret/IME. A changed text declaration (e.g. reference picker result) updates that same control without restoring the previous value. An input edited after command dispatch rejects that response's stale text. External replacement during IME composition waits until composition ends. Scroll and focus are retained where the same visible control survives; removed/retyped/reparented controls cannot guarantee IME continuity. Packs own drafts for absent nodes and must supply them on return. No node/slot patch wire API is introduced; full XML is reconciled by the host.",
        Selection = "EditorCommandResult.PickObject = new EditorObjectPicker { Kind, Pack, Title, Command }. The host lists the project's indexed objects and invokes that pack's registered Text command with the selected Key. Cancel does not invoke it. Read the document again in the callback before proposing an edit. Index metadata is not proof of runtime behavior.",
        CatalogExample = "var catalog = project as IEditorProjectCatalog ?? throw new NotSupportedException(); var entries = catalog.ListObjects(invocation.Arguments[\"kind\"]); var images = catalog.ListAssets(); // Resolve this consumer's XML icon references, then catalog.ReadAsset(path).DataUrl. Return View to render slots, or PickObject to request a selection. Return DocumentChanges for reviewed source edits.",
        Document = new[] { "Path", "Pack", "Kind", "Editable", "Text", "DocumentHash", "DiskHash", "Draft", "DiskChanged", "Partial" },
        Proposal = "Return List<EditorDocumentChange> in EditorCommandResult.DocumentChanges. Each change needs Path, ExpectedHash=the observed DocumentHash, complete replacement Text, and Intent. Read the complete, clean file in the SAME invocation. One change per document, at most 100. No direct save method exists: the host shows one review and saves only selected files with conflict checks and undo data.",
        Limits = "Declared project text files only; read-only contracts/configuration stay read-only. Relative paths and existing project path checks apply. Reads do not open documents or fabricate assistant reads. At most 64 requests and 2 million returned characters per command; maximumCharacters 1..2000000. Data service lifetime is one command; returned documents are detached snapshots. No auto build/run/reload follows a save.",
        Example = """
            public sealed class ChangeDocument : EditorProjectCommand {
                public override UiValueKind Payload => UiValueKind.Text;
                public override EditorCommandResult Execute(EditorInvocation invocation, IEditorProjectData project) {
                    var document = project.ReadDocument(invocation.Arguments["path"]);
                    if (!document.Editable || document.Partial || document.Draft || document.DiskChanged)
                        return new() { Message = "Read and reconcile the complete editable document first." };
                    return new() { DocumentChanges = [new() {
                        Path = document.Path, ExpectedHash = document.DocumentHash,
                        Text = invocation.Payload, Intent = "Apply the user's document edit"
                    }] };
                }
            }
            // Register with registry.Command("my.editor.changeDocument", new ChangeDocument());
            // Declare a matching Text command and path Argument in editor.xml.
            """,
        Sources = new[] { "editor/Confectory.Editor.Contracts/ProjectData.cs", "editor/Confectory.Editor.Contracts/Elements.cs", "editor/Confectory.Editor.Contracts/Extensions.cs" },
        Documentation = "docs/EDITOR_PACKS.md#프로젝트-데이터-접근; docs/ELEMENT_EDITOR.md"
    };
}
