using System.Text;
using Confectory.EditorPacks;
using Confectory.Contracts.UI;
using Confectory.Runtime.UI;
using Confectory.Workspace;

internal static class ParticipantLifecycleVerification
{
    public static void Run(EditorStudioPresentation presentation, IUiBackend backend, string root, string platform, Action<bool, string> check, Action<Action, string> reject)
    {
        void Check(bool value, string label) => check(value, label + " on " + platform);
        void Reject(Action action, string label) => reject(action, label + " on " + platform);
        string folder = Path.Combine(root, "Lifecycle", platform), privateRoot = Path.Combine(folder, "Private");
        var project = NewProject.Create(Path.Combine(folder, "Project", "Lifecycle.packproject"));
        var roles = ProjectStudio.Load(project); var directory = new AiDirectory();
        var agent = directory.AddAgent("Lifecycle Agent", new() { Provider = "openai", Model = "fixture-model" }, "synthetic-reference");
        var helper = directory.CreateHelper(agent.Id, "Global Helper"); directory.Remember(helper.Id, "Significant private context", "");
        var hub = new CollaborationWorkspace(Path.Combine(folder, "Presence")); string hubFile = Path.Combine(folder, "Presence", "collaboration.json");
        bool running = false, failDirectory = false, failCleanup = false; int cleanup = 0;
        string directoryFile = Path.Combine(privateRoot, "ai-directory.json");
        void SaveDirectory() { if (failDirectory) throw new IOException("fixture private write failure"); directory.Save(directoryFile); }
        using var workspace = presentation.Actions.Workspace(presentation, backend, directory, project, roles, hub, SaveDirectory, (_, _) => { }, _ => { }, _ => running, () => true,
            removed: _ => { cleanup++; if (failCleanup) throw new IOException("fixture native cleanup failure"); });
        var joined = workspace.JoinHelper(helper.Id);
        var remote = hub.Register("remote", "Remote", ParticipantKind.AI, ParticipantPermission.Work); remote.HelperId = helper.Id; remote.OwnerId = "other-owner";
        var view = hub.View("human", joined.Id); view.X = 33; var presence = hub.Presence(joined.Id);
        var room = new DocumentRoom(); room.Participants.Add(joined.Id); room.Participants.Add(remote.Id); hub.State.Rooms.Add(room);
        hub.Post(joined.Id, "Public audit evidence"); var work = hub.Begin("audit", joined.Id, "Significant work"); hub.Save();
        running = true; Reject(() => workspace.RemoveHelper(helper.Id), "running Helper removal is rejected before native cleanup");
        Check(cleanup == 0 && roles.HelperIds.Contains(helper.Id) && hub.State.Participants.Contains(joined), "rejected removal preserves roles and character"); running = false;
        File.Move(hubFile, hubFile + ".backup"); Directory.CreateDirectory(hubFile);
        Reject(() => workspace.RemoveHelper(helper.Id), "participant write failure is reported");
        Check(cleanup == 0 && hub.State.Participants.Contains(joined) && hub.State.Views.Contains(view) && hub.State.Presence.Contains(presence) && room.Participants.Contains(joined.Id) && ProjectStudio.Load(project).HelperIds.Contains(helper.Id), "failed removal restores roles, views, presence and room membership");
        Check(!hub.State.ArchivedParticipants.Any(p => p.Id == joined.Id), "failed disconnect cannot leave a duplicate archived identity");
        Directory.Delete(hubFile); File.Move(hubFile + ".backup", hubFile);
        workspace.RemoveHelper(helper.Id);
        Check(cleanup == 1 && !roles.HelperIds.Contains(helper.Id) && roles.MainHelperId.Length == 0 && !hub.State.Participants.Contains(joined) && hub.State.Participants.Contains(remote), "committed removal affects only controlled participants and clears MAIN");
        Check(helper.Enabled && helper.Memories.Any(m => m.Text == "Significant private context") && hub.State.Messages.Any(m => m.Text == "Public audit evidence") && hub.State.Work.Contains(work), "removal preserves global memory and audit evidence");
        Check(hub.State.ArchivedParticipants.Single(p => p.Id == joined.Id).OwnerId == "human" && hub.State.ArchivedParticipants.All(p => p.Id != remote.Id), "Helper disconnect archives only owned participant identity for history recovery");
        Check(!hub.State.Views.Contains(view) && !hub.State.Presence.Contains(presence) && room.Participants.SequenceEqual(new[] { remote.Id }), "removal clears only detached character presentation and membership");
        var collision = new Participant { Id = joined.Id, Kind = ParticipantKind.Human, Name = "Identity collision" }; hub.State.Participants.Add(collision);
        Reject(() => workspace.JoinHelper(helper.Id), "archived identity cannot overwrite an active identity collision"); hub.State.Participants.Remove(collision);
        hub.State.ArchivedParticipants.Add(new Participant { Id = "foreign-archive", Kind = ParticipantKind.AI, HelperId = helper.Id, OwnerId = "other-owner", AiRole = ParticipantAiRole.Helper });
        var archivedIdentity = hub.State.ArchivedParticipants.Single(p => p.Id == joined.Id); archivedIdentity.Permissions |= ParticipantPermission.Apply;
        var currentOwner = hub.Require("human", ParticipantPermission.Work); var ownerPermissions = currentOwner.Permissions;
        currentOwner.Permissions &= ~ParticipantPermission.Apply;
        Reject(() => workspace.JoinHelper(helper.Id), "archived Apply permission cannot bypass a revoked owner grant");
        Check(hub.State.ArchivedParticipants.Contains(archivedIdentity) && !hub.State.Participants.Any(p => p.Id == joined.Id) && !roles.HelperIds.Contains(helper.Id), "denied archived permission restoration preserves history and inactive participation");
        currentOwner.Permissions = ownerPermissions;
        var rejoined = workspace.JoinHelper(helper.Id); workspace.JoinHelper(helper.Id);
        Check(rejoined.Permissions.HasFlag(ParticipantPermission.Apply), "explicit authorized rejoin preserves the archived grant without inventing a new permission");
        Check(hub.State.ArchivedParticipants.Any(p => p.Id == "foreign-archive"), "owned rejoin leaves foreign archived identity untouched");
        Check(hub.State.Participants.Count(p => p.HelperId == helper.Id && p.OwnerId == "human") == 1 && ProjectStudio.Load(project).HelperIds.Contains(helper.Id) && rejoined.Id == joined.Id && !hub.State.ArchivedParticipants.Any(p => p.Id == joined.Id), "remove then rejoin restores the same project identity and leaves one active participant");
        failCleanup = true; Reject(() => workspace.RemoveHelper(helper.Id), "native cleanup failure is reported after persistence"); failCleanup = false;
        Check(!new CollaborationWorkspace(Path.Combine(folder, "Presence")).State.Participants.Any(p => p.Id == rejoined.Id) && !roles.HelperIds.Contains(helper.Id), "native cleanup failure cannot resurrect committed participation");
        string missing = Guid.NewGuid().ToString("N"); roles.AddHelper(missing); roles.Save(project); workspace.RemoveHelper(missing);
        Check(!ProjectStudio.Load(project).HelperIds.Contains(missing), "missing private profile can still be detached from project roles");
        var orphan = workspace.JoinHelper(helper.Id); roles.RemoveHelper(helper.Id); roles.Save(project); workspace.PruneHelpers();
        Check(!hub.State.Participants.Contains(orphan) && hub.State.Participants.Contains(remote), "saved-role pruning retains another owner's matching Helper");
        var worker = hub.Register("worker", "Ordinary Worker", ParticipantKind.AI, ParticipantPermission.Talk | ParticipantPermission.Work); worker.AgentId = agent.Id;
        byte[] experience = Encoding.UTF8.GetBytes("[{\"User\":\"private initial experience\"}]");
        int helpers = directory.Helpers.Count;
        Reject(() => workspace.Promote(remote.Id, "Forbidden", experience, privateRoot), "promotion denies another owner's participant");
        Reject(() => workspace.Promote(worker.Id, "", experience, privateRoot), "promotion validates name before writes");
        Reject(() => workspace.Promote(worker.Id, "Relative", experience, "relative-root"), "promotion rejects relative private storage");
        running = true; Reject(() => workspace.Promote(worker.Id, "Running", experience, privateRoot), "promotion rejects an active worker"); running = false;
        Check(directory.Helpers.Count == helpers && worker.HelperId.Length == 0 && !Directory.Exists(Path.Combine(privateRoot, "Helpers")), "rejected promotion has no identity or private-history side effects");
        failDirectory = true; Reject(() => workspace.Promote(worker.Id, "Retry Helper", experience, privateRoot), "promotion reports private directory failure"); failDirectory = false;
        Check(worker.Name == "Ordinary Worker" && worker.HelperId.Length == 0 && directory.Helpers.Count == helpers && !Directory.GetDirectories(Path.Combine(privateRoot, "Helpers")).Any(), "failed private promotion removes staged history and restores identity");
        File.Move(hubFile, hubFile + ".backup"); Directory.CreateDirectory(hubFile);
        Reject(() => workspace.Promote(worker.Id, "Retry Helper", experience, privateRoot), "promotion reports presence failure");
        Check(worker.HelperId.Length == 0 && directory.Helpers.Count == helpers && ProjectStudio.Load(project).HelperIds.Count == 0 && AiDirectory.Load(directoryFile).Helpers.Count == helpers, "failed promotion compensates persisted roles and private directory");
        Directory.Delete(hubFile); File.Move(hubFile + ".backup", hubFile);
        Action observer = () => throw new IOException("fixture observer failure after publication"); hub.Changed += observer;
        Reject(() => workspace.Promote(worker.Id, "Observer retry", experience, privateRoot), "post-write observer failure is explicit during promotion"); hub.Changed -= observer;
        Check(worker.HelperId.Length == 0 && !new CollaborationWorkspace(Path.Combine(folder, "Presence")).State.Participants.Single(p => p.Id == worker.Id).HelperId.Any() && ProjectStudio.Load(project).HelperIds.Count == 0, "promotion restores saved presence after an observer fails");
        hub.Changed += observer;
        Reject(() => workspace.JoinHelper(helper.Id), "post-write observer failure is explicit during Join"); hub.Changed -= observer;
        Check(!new CollaborationWorkspace(Path.Combine(folder, "Presence")).State.Participants.Any(p => p.HelperId == helper.Id && p.OwnerId == "human") && ProjectStudio.Load(project).HelperIds.Count == 0, "Join compensation prevents a saved phantom participant after observer failure");
        Check(hub.State.ArchivedParticipants.Any(p => p.Id == joined.Id) && new CollaborationWorkspace(Path.Combine(folder, "Presence")).State.ArchivedParticipants.Any(p => p.Id == joined.Id), "failed rejoin restores archived history identity in memory and on disk");
        var promoted = workspace.Promote(worker.Id, "  Promoted Helper  ", experience, privateRoot);
        Check(promoted.Name == "Promoted Helper" && worker.Name == promoted.Name && worker.HelperId == promoted.Id && promoted.AgentId == agent.Id && roles.HelperIds.Contains(promoted.Id), "explicit promotion links worker, private Helper and project role");
        Check(File.ReadAllBytes(Path.Combine(privateRoot, "Helpers", promoted.Id, "first-experience.json")).SequenceEqual(experience), "promotion preserves exact initial private experience");
        Check(!File.ReadAllText(hubFile).Contains("private initial experience") && !File.ReadAllText(project.Manifest).Contains("synthetic-reference"), "promotion exports no private history or credential reference");
        hub.Changed += observer;
        Reject(() => workspace.RemoveHelper(promoted.Id), "post-write observer failure is explicit during removal"); hub.Changed -= observer;
        Check(hub.State.Participants.Contains(worker) && new CollaborationWorkspace(Path.Combine(folder, "Presence")).State.Participants.Any(p => p.Id == worker.Id) && ProjectStudio.Load(project).HelperIds.Contains(promoted.Id), "removal compensates saved presence and roles after observer failure");
        Check(!hub.State.ArchivedParticipants.Any(p => p.Id == worker.Id), "failed promoted Helper removal leaves no archived duplicate");
        Reject(() => workspace.Promote(worker.Id, "Again", experience, privateRoot), "repeat promotion cannot duplicate private identities");
        var participants = presentation.Actions.Participants(directory, hub); var human = hub.Require("human", ParticipantPermission.Work); human.Permissions = ParticipantPermission.None;
        var remotePlacement = participants.Move(remote.Id, 999, -4, 200, 160, 100, 80);
        Check(remotePlacement == new EditorStudioPlacement(100, 0, 1) && remote.X == 24 && remote.Y == 24 && hub.State.Views.All(v => v.Viewer == "human"), "viewer may arrange another owner's character without changing public coordinates");
        participants.Display(remote.Id, CharacterDisplay.Compact);
        Check(hub.View("human", remote.Id).Display == CharacterDisplay.Compact, "read-only viewer display choice remains local");
        Reject(() => participants.RefreshHelperName(promoted.Id), "local placement authority cannot rename private identities"); human.Permissions = ParticipantPermission.Talk | ParticipantPermission.Work | ParticipantPermission.Apply;
        var scaled = participants.Move(worker.Id, 999, 999, 120, 100, 200, 160);
        Check(Math.Abs(scaled.X - 18) < .00001 && Math.Abs(scaled.Y - 18.4) < .00001 && Math.Abs(scaled.Scale - .51) < .00001, "shared logical layout scales and clamps character bounds");
        participants.CommitPlacement(worker.Id);
        Check(new CollaborationWorkspace(Path.Combine(folder, "Presence")).View("human", worker.Id).X == scaled.X, "explicit drag completion persists placement through reopen");
        string saved = File.ReadAllText(hubFile); participants.Move(worker.Id, 3, 4, 120, 100, 200, 160);
        Check(File.ReadAllText(hubFile) == saved, "drag motion stays local until explicit completion");
        Reject(() => participants.Move(worker.Id, double.NaN, 0, 200, 160, 100, 80), "placement rejects nonfinite pointer coordinates");
        Reject(() => participants.Layout(worker.Id, -1, 160, 100, 80), "layout rejects invalid native dimensions");
        hub.Changed += observer;
        Reject(() => participants.Display(worker.Id, CharacterDisplay.Full), "post-write observer failure is explicit during display change"); hub.Changed -= observer;
        Check(hub.View("human", worker.Id).Display == CharacterDisplay.Hidden && new CollaborationWorkspace(Path.Combine(folder, "Presence")).View("human", worker.Id).Display == CharacterDisplay.Hidden, "failed display change restores both local and saved view");
        Reject(() => participants.Display(worker.Id, (CharacterDisplay)99), "display rejects invalid enum values");
        File.Move(hubFile, hubFile + ".backup"); Directory.CreateDirectory(hubFile);
        Reject(() => participants.CommitPlacement(worker.Id), "drag persistence failure is explicit");
        Check(hub.View("human", worker.Id).X == 3, "failed drag completion retains local draft for retry");
        Reject(() => participants.Move(worker.Id, 9, 8, 120, 100, 200, 160, true), "immediate move persistence failure is explicit");
        Check(hub.View("human", worker.Id).X == 3 && hub.View("human", worker.Id).Y == 4, "failed immediate move restores previous local placement");
        Directory.Delete(hubFile); File.Move(hubFile + ".backup", hubFile); participants.CommitPlacement(worker.Id);
        Check(new CollaborationWorkspace(Path.Combine(folder, "Presence")).View("human", worker.Id).X == 3, "explicit placement retry saves the retained local draft");
        var standalone = NewProject.Create(Path.Combine(folder, "Standalone", "Standalone.packproject"));
        var standaloneXml = System.Xml.Linq.XDocument.Load(standalone.Manifest); standaloneXml.Root!.SetAttributeValue("id", "confectory.editor"); standaloneXml.Save(standalone.Manifest);
        standalone = WorkspaceProject.Open(standalone.Manifest); var standaloneRoles = ProjectStudio.Load(standalone);
        using var globalWorkspace = presentation.Actions.Workspace(presentation, backend, directory, standalone, standaloneRoles, hub, SaveDirectory, (_, _) => { }, _ => { }, _ => false);
        failDirectory = true; Reject(() => globalWorkspace.RemoveHelper(promoted.Id), "standalone removal reports private persistence failure"); failDirectory = false;
        Check(promoted.Enabled && hub.State.Participants.Contains(worker), "failed standalone removal keeps enabled global Helper and character");
        globalWorkspace.RemoveHelper(promoted.Id);
        Check(!promoted.Enabled && !AiDirectory.Load(directoryFile).Helpers.Single(h => h.Id == promoted.Id).Enabled && !hub.State.Participants.Contains(worker) && File.Exists(Path.Combine(privateRoot, "Helpers", promoted.Id, "first-experience.json")), "standalone removal disables rather than deletes global identity and experience");
    }
}
