// Optional UI verification: npm install --no-save playwright, then node tools/browser-smoke.mjs.
// CHROME_PATH can select an installed Chromium. Keep the game host running on 5187.
import {createRequire} from 'node:module';
import {mkdir} from 'node:fs/promises';
import {spawn} from 'node:child_process';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const host=process.argv.includes('--host')?spawn(process.env.DOTNET||'dotnet',['src/Golemancer.Host/bin/Debug/net10.0/Golemancer.Host.dll'],{stdio:'ignore'}):null;
process.on('exit',()=>host?.kill());
if(host)for(let i=0;i<100;i++){try{if((await fetch('http://127.0.0.1:5187/api/meta')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
const page=await browser.newPage({viewport:{width:1440,height:900},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await mkdir('TestResults',{recursive:true});
await page.goto('http://127.0.0.1:5187');
await page.waitForFunction(()=>document.querySelector('#loading').textContent.includes('준비 완료'));
await page.screenshot({path:'TestResults/01-title.png'});
await page.getByRole('button',{name:'공방 문 열기'}).click();
await page.waitForSelector('#dialogue:not([hidden])');
await page.screenshot({path:'TestResults/02-dialogue.png'});
await page.locator('#dialogueNext').click();
await page.waitForSelector('#dialogue[hidden]',{state:'attached'});
await page.screenshot({path:'TestResults/03-workshop.png'});
await page.keyboard.press('d');
await page.waitForFunction(async()=>{const s=await(await fetch('/api/state')).json();return s.objects[s.controlledId].x===10;});
await page.keyboard.press('b');
await page.waitForSelector('[data-build="herb_fumigator"]');
await page.screenshot({path:'TestResults/04-build-menu.png'});
await page.keyboard.press('Escape');
await page.keyboard.press('r');
await page.waitForFunction(async()=>{const s=await(await fetch('/api/state')).json();return !!s.objects[s.controlledId].recording;});
await page.keyboard.press('d');
await page.waitForFunction(async()=>{const s=await(await fetch('/api/state')).json();return s.objects[s.controlledId].x===11;});
await page.keyboard.press('r');
await page.waitForFunction(async()=>{const s=await(await fetch('/api/state')).json();return Object.keys(s.recordings).length===1;});
await page.locator('#routinesButton').click();await page.waitForSelector('.routine');
await page.screenshot({path:'TestResults/05-routines.png'});
await page.keyboard.press('Escape');
await page.keyboard.press('Escape');
await page.locator('[data-save]').click();
const before=await page.evaluate(async()=>await(await fetch('/api/state')).json());
await page.waitForTimeout(500);
const paused=await page.evaluate(async()=>await(await fetch('/api/state')).json());
if(before.time!==paused.time)throw Error('Pause did not stop the simulation');
await page.locator('[data-load="manual"]').click();
await page.waitForSelector('#modal[hidden]',{state:'attached'});
await page.waitForFunction(async()=>{const s=await(await fetch('/api/state')).json();return !s.paused&&Object.keys(s.recordings).length===1;});
async function clickTile(x,y){await page.waitForTimeout(500);const a=await page.evaluate(async()=>{const s=await(await fetch('/api/state')).json();return s.objects[s.controlledId];});await page.mouse.click((x+.5-a.x-.5)*48+720,(y+.5-a.y-.2)*48+467.5);}
await clickTile(17,26);
await page.waitForFunction(async()=>{const s=await(await fetch('/api/state')).json();return s.objects[s.controlledId].inventory.common_herb>=3;},{timeout:20000});
await clickTile(10,22);
await page.waitForSelector('#transferItem');
await page.locator('#transferItem').selectOption('common_herb');
await page.locator('#transferQuantity').fill('3');
await page.locator('[data-transfer="give"]').click();
await page.waitForFunction(async()=>{const s=await(await fetch('/api/state')).json();return s.objects['shelf-1'].inventory.common_herb>=1;},{timeout:20000});
await page.screenshot({path:'TestResults/06-stocked-shelf.png'});
await page.waitForFunction(async()=>{const s=await(await fetch('/api/state')).json();return s.values.sales>=1;},{timeout:20000});
await page.keyboard.press('Escape');
for(const size of [{width:1280,height:800},{width:1920,height:1080}]){await page.setViewportSize(size);await page.screenshot({path:`TestResults/workshop-${size.width}.png`});}
if(errors.length)throw Error(errors.join('\n'));
console.log('PASS: title, Enrin portrait dialogue, movement, building menu, recording, pause, save/load, mouse harvesting, exact shelf transfer, customer sale, 3 desktop viewports; no browser exceptions.');
await browser.close();
host?.kill();
